Jwt token
layzimayner/book-store pull request #14
Opened 2024-11-28 11:15 UTC by layzimayner

2024-11-28 13:48 UTC, Elena-Bruyako requested changes
Good job! Let's fix some comments

2024-11-28 13:48 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/config/OpenApiConfig.java
> +                .components(new Components().addSecuritySchemes("BearerAuth",
let's create constants for strings

2024-11-28 13:48 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/controller/AuthenticationController.java
> +    @PostMapping("/login")
let's add swagger annotations

2024-11-28 13:48 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer")) {
create constant for `"Bearer"`

2024-11-28 13:48 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
```suggestion
            return bearerToken.substring(constant.length());
```

2024-11-28 13:48 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader("Authorization");
let's use Spring constant 
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```

2024-11-29 07:09 UTC, liliia-ponomarenko approved these changes
Good job! A few minor comments ;)

2024-11-29 07:09 UTC, liliia-ponomarenko commented on src/main/java/com/example/demo/security/JwtAuthenticationFilter.java
> +    private static final String ENCODING_SCHEME = "Bearer";
```suggestion
    private static final String ENCODING_SCHEME = "Bearer ";
```

2024-11-29 07:09 UTC, liliia-ponomarenko commented on src/main/java/com/example/demo/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(ENCODING_SCHEME.length() + 1);
```suggestion
            return bearerToken.substring(ENCODING_SCHEME.length());
```

2024-11-29 07:09 UTC, liliia-ponomarenko commented on src/main/resources/application.properties
> +jwt.secret=1jerjncvokjfvwlfjfvnwhjhfnv
is it enough length of secret?

2024-11-29 12:04 UTC, merged