Add category model
layzimayner/book-store pull request #15
Opened 2024-11-29 22:02 UTC by layzimayner

2024-12-02 07:03 UTC, liliia-ponomarenko requested changes
Good job! Let’s improve your solution ;)

2024-12-02 07:03 UTC, liliia-ponomarenko commented on src/main/java/com/example/demo/controller/CategoryController.java
> +@Validated
How does this annotation work? Do you use it?

2024-12-02 07:03 UTC, liliia-ponomarenko commented on src/main/java/com/example/demo/controller/CategoryController.java
> +    @PostMapping
ResponseStatus.CREATED

2024-12-02 07:03 UTC, liliia-ponomarenko commented on src/main/java/com/example/demo/controller/CategoryController.java
> +    public List<CategoryDto> getAll(Pageable pageable) {
better return Page (optional)

2024-12-02 07:03 UTC, liliia-ponomarenko commented on src/main/java/com/example/demo/controller/CategoryController.java
> +            @PathVariable @Valid Long id,
How are you validating an ID? You can use Positive

2024-12-02 07:03 UTC, liliia-ponomarenko commented on src/main/java/com/example/demo/controller/CategoryController.java
> +    @GetMapping("/by-categoryId")
following task description `/api/categories/{id}/books`

2024-12-02 07:03 UTC, liliia-ponomarenko commented on src/main/java/com/example/demo/dto/book/CreateBookRequestDto.java
> +    private Set<Long> categoriesIds;
Can a book exist without a Category? Let’s  add NotEmpty validator

2024-12-02 07:03 UTC, liliia-ponomarenko commented on src/main/java/com/example/demo/model/Book.java
> +    @ManyToMany(fetch = FetchType.LAZY)
```suggestion
    @ManyToMany
```
It's default fetch type

2024-12-02 07:03 UTC, liliia-ponomarenko commented on src/main/java/com/example/demo/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
```suggestion
    @ManyToMany
```
Let’s  use join fetch or EntityGraph

2024-12-02 07:03 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/08-create-categories-table.yaml
> +                  type: VARCHAR(50)
validate request dto length

2024-12-02 07:03 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/08-create-categories-table.yaml
> +                    nullable: false
add one empty line at the end of the file (check other files)

2024-12-02 13:11 UTC, Elena-Bruyako requested changes
see comments, 
build failed, fix it

2024-12-02 13:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/controller/CategoryController.java
> +    public CategoryDto getCategoryById(Long id) {
```suggestion
    public CategoryDto getCategoryById(@PathVariable @Positive Long id) {
```

2024-12-02 13:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/controller/CategoryController.java
> +    @GetMapping
```suggestion
    @GetMapping("/{id}")
```

2024-12-02 13:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/controller/CategoryController.java
> +    public void deleteCategory(Long id) {
```suggestion
    public void deleteCategory(@PathVariable @Positive Long id)) {
```

2024-12-02 13:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/controller/CategoryController.java
> +    public List<BookDtoWithoutCategoryIds> getBooksByCategoryId(@RequestParam Long categoryId) {
```suggestion
    public List<BookDtoWithoutCategoryIds> getBooksByCategoryId(@PathVariable @Positive Long categoryId) {
```

2024-12-02 13:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/dto/book/CreateBookRequestDto.java
> +    @NotBlank
```suggestion
    @NotEmpty
```

2024-12-02 13:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +    @Column(nullable = false)
```suggestion
```

2024-12-02 13:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +    private Set<Category> categories;
```suggestion
    private Set<Category> categories = new HashSet<>();
```

2024-12-02 13:11 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
don't use Eager fetchtype

```suggestion
    @ManyToMany
```

2024-12-03 06:39 UTC, liliia-ponomarenko approved these changes
Great! 😊

2024-12-03 06:39 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/09-create-books-categories-table.yaml
add one empty line

2024-12-03 07:04 UTC, merged