add readme file
layzimayner/book-store pull request #20
Opened 2024-12-30 13:17 UTC by layzimayner

2024-12-30 13:24 UTC, layzimayner commented
you coud see full version in the

2025-01-12 09:15 UTC, Elena-Bruyako requested changes
see comments

2025-01-12 09:15 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/mapper/CartMapper.java
> +    @Mapping(source = "quantity", target = "quantity")
```suggestion
    @Mapping(source = "book.id", target = "bookId")
    @Mapping(source = "book.title", target = "bookTitle")
```

2025-01-12 09:15 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/controller/CartController.java
> +    public CartItemResponseDto addItemToCart(
```suggestion
    public CartDto addItemToCart(
```

2025-01-12 09:15 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/controller/CartController.java
> +    public UpdatedQuantityDto updateItemQuantity(
```suggestion
    public CartDto updateItemQuantity(
```

2025-01-12 09:15 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/dto/cart/CartDto.java
> +    private Long id;
```suggestion
    private Long id;
    private Long userId;
```

2025-01-12 09:15 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/service/OrderServiceImpl.java
> +        Page<Order> ordersPage = orderRepository.findAllByUserId(userId, pageable);
why did you change this method?

2025-01-12 09:15 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/service/UserServiceImpl.java
> +        return userMapper.toUserResponseDto(sevedUser);
```suggestion
        userRepository.save(user);
        cartService.createShoppingCartForUser(user);
        return userMapper.toUserResponseDto(user);
```

2025-01-14 06:39 UTC, liliia-ponomarenko approved these changes
Good job! A few minor comments ;)

2025-01-14 06:39 UTC, liliia-ponomarenko commented on src/main/java/com/example/demo/dto/cart/CartDto.java
> +public class CartDto {
```suggestion
public class CartDto {
         private Long id;
```

2025-01-14 06:39 UTC, liliia-ponomarenko commented on README.md
> +6. [Postmen and Swagger](#postman-and_swagger)
```suggestion
6. [Postman and Swagger](#postman-and_swagger)
```

2025-01-14 06:39 UTC, liliia-ponomarenko commented on README.md
> +   book-store\src\main\resources\book store.postman_collection.json
don't overload the readme file with collection import instructions

2025-01-14 11:19 UTC, merged