new PR
layzimayner/book-store pull request #7
Opened 2024-11-11 15:21 UTC by layzimayner

2024-11-11 15:38 UTC, Elena-Bruyako requested changes
Let's check task description
Add class with @SpringBootApplication annotation that will have a CommandLineRunner bean where you call BookService methods

Check IMPORTANT section
provide pom file
provide application.properties files

2024-11-11 15:38 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/config/AppConfig.java
> +public class AppConfig {
remove

2024-11-11 15:38 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +@Data
don't use Data for entities

2024-11-11 15:38 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +public class Book {
add `@Table`

2024-11-11 15:38 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +    private String title;
add required constraints

2024-11-11 15:38 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/repository/BookRepositoryImpl.java
> +@Repository
```suggestion
@Repository
@RequiredArgsConstructor
```

2024-11-11 15:38 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/repository/BookRepositoryImpl.java
> +    }
```suggestion
    private final SessionFactory sessionFactory;
```

2024-11-11 15:38 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/repository/BookRepositoryImpl.java
> +            throw new RuntimeException("Can't save data", e);
message should be more informative 
```suggestion
            throw new DataProcessingException("Can't save data", e);
```

2024-11-11 15:38 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/repository/BookRepositoryImpl.java
> +        }
add catch block

2024-11-11 15:38 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/repository/BookRepositoryImpl.java
> +            return query.list();
```suggestion
            return query.getResultList();
```

2024-11-11 15:38 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/service/BookServiceImpl.java
> +@Service
```suggestion
@Service
@RequiredArgsConstructor
```

2024-11-11 15:38 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/service/BookServiceImpl.java
> +    private BookRepository bookRepository;
```suggestion
    private final BookRepository bookRepository;
```

2024-11-13 10:01 UTC, layzimayner commented
I created pom, application.properties and test/application.properties in last PR

2024-11-13 18:12 UTC, Elena-Bruyako requested changes
see comments

2024-11-13 18:12 UTC, Elena-Bruyako commented on pom.xml
> +			<groupId>jakarta.validation</groupId>
remove dependency

2024-11-13 18:12 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +@Entity
```suggestion
@Entity
@Getter
@Setter
```

2024-11-13 18:12 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +    public void setId(Long id) {
remove all set and get methods

2024-11-13 18:12 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +    @NotBlank(message = "Title is required")
use for all required columns

```suggestion
    @Column(nullable = false)
```

2024-11-13 18:53 UTC, Elena-Bruyako requested changes
one comment

2024-11-13 18:53 UTC, Elena-Bruyako commented on src/main/java/com/example/demo/model/Book.java
> +    @DecimalMin(value = "0.0", inclusive = false, message = "Price must be greater than 0")
```suggestion
    @Column(nullable = false)
```

2024-11-13 19:04 UTC, Elena-Bruyako approved these changes

2024-11-15 09:46 UTC, Elena-Bruyako commented
Changes were already approved, after approving merge PR, create branch and implement next HW
<img width="963" alt="Screenshot 2024-11-15 at 11 45 54" src="https://github.com/user-attachments/assets/ef3c3d81-fdac-4789-b61f-086e0f86a152">

2024-11-15 10:04 UTC, closed without merging